development:
  adapter: redis
  url: redis://localhost:6379/1

test:
  adapter: test

production:
  adapter: redis
  url: <%= Rails.application.secrets.action_cable_redis_url %>
  channel_prefix: exercism_production
