test:
  accounts:
    -
      slug: :ruby
      consumer_key: KEY
      consumer_secret: SECRET
      access_token: TOKEN
      access_token_secret: TOKEN_SECRET
    -
      slug: :main
      consumer_key: MAIN_KEY
      consumer_secret: MAIN_SECRET
      access_token: MAIN_TOKEN
      access_token_secret: MAIN_TOKEN_SECRET

